---
version: 2
registries:
  github:
    type: maven-repository
    url: https://maven.pkg.github.com/ribbons/android-rsync
    username: ribbons
    password: ${{secrets.PKG_TOKEN}}

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    allow:
      - dependency-name: reactivecircus/android-emulator-runner

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    registries:
      - github
