---
PreCommit:

  ALL:
    problem_on_unmodified_line: warn

  GradleCheck:
    description: Run check task in Gradle
    enabled: true
    required_executable: ./gradlew
    flags: check

  TrailingWhitespace:
    enabled: true
    exclude:
      - metadata/en-US/full_description.txt

  FileEncoding:
    description: Check text files are valid UTF-8
    enabled: true

  SingleNewlineAtEof:
    description: Check text files end with a single newline
    enabled: true
    exclude: .idea/**/*

  Copyright:
    description: Check copyright notices are present and updated
    enabled: true
    exclude: gradlew*

  YamlLint:
    enabled: true
    on_warn: fail

  TestedApiLevels:
    description: Check CI instrumented test coverage of API levels
    enabled: true
    include: app/build.gradle.kts

  Metadata:
    description: Check that metadata matches the readme
    enabled: true
    include:
      - README.md
      - metadata/en-US/short_description.txt
      - metadata/en-US/full_description.txt
