---
# Copyright © 2021-2024 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release
on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Generate release bundle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleRelease
        env:
          PKG_USERNAME: github-actions
          PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign release apk
        run: |
          apksigner=$(find "$ANDROID_SDK_ROOT/build-tools/" -name apksigner | \
              sort -r | head -n1)
          cp app/build/outputs/apk/release/app-release{-unsigned,}.apk
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > release.p12
          $apksigner sign -ks release.p12 \
              --ks-pass pass:'${{ secrets.RELEASE_KEYSTORE_PASSWORD }}' \
              app/build/outputs/apk/release/app-release.apk
          rm release.p12

      - name: Upload signed apk as release asset
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: com.nerdoftheherd.tasker.rsync_${{
            github.event.release.tag_name }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Trigger website update
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PUBLISH_NOTH_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'nerdoftheherd.com',
              workflow_id: 'publish.yml',
              ref: 'master'
            })
